# Generated by Django 2.0.1 on 2018-01-26 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugdemo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
